joint_limits:
  JointA:
    has_position_limits: true
    min_position: -3.14
    max_position: 3.14
    has_velocity_limits: false
    max_velocity: 0
    has_acceleration_limits: false
    max_acceleration: 0.0
    has_jerk_limits: false
    max_jerk: 0
    has_effort_limits: false
    max_effort: 12
  JointB:
    has_position_limits: true
    min_position: -3.14
    max_position: 0.1
    has_velocity_limits: false
    max_velocity: 0
    has_acceleration_limits: false
    max_acceleration: 0.0
    has_jerk_limits: false
    max_jerk: 0
    has_effort_limits: false
    max_effort: 12
  JointC:
    has_position_limits: true
    min_position: -3.14
    max_position: 3.14
    has_velocity_limits: false
    max_velocity: 0
    has_acceleration_limits: false
    max_acceleration: 0.0
    has_jerk_limits: false
    max_jerk: 0
    has_effort_limits: false
    max_effort: 12
  JointD:
    has_position_limits: true
    min_position: -3.14
    max_position: 3.14
    has_velocity_limits: false
    max_velocity: 0
    has_acceleration_limits: false
    max_acceleration: 0.0
    has_jerk_limits: false
    max_jerk: 0
    has_effort_limits: false
    max_effort: 12