assembly9:
  jointA_position_controller:
    type: position_controllers/JointPositionController
    joint: JointA
  jointB_position_controller:
    type: position_controllers/JointPositionController
    joint: JointB
  jointC_position_controller:
    type: position_controllers/JointPositionController
    joint: JointC
  jointD_position_controller:
    type: position_controllers/JointPositionController
    joint: JointD
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  
